### ISSUE TITLE
pudl0016 Digital Library Bookshelf

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/pudl-migration#15] opened 2020-05-27 20:12 UTC

**Comment by cwulfman** [comment] 2020-05-28 14:12
Duplicate of #4

**Comment by kelea99** [comment] 2020-06-25 18:49
done?|collection|bibid|title
-----|----------|-----|-----
|x|pudl0091|4109657|[Album containing 1000 wood engravings]
|x|pudl0006|3805972|Arthur Mendel : June 6, 1905 - October 14, 1979
|x|pudl0064|2397415|Atlas universel de géographie physique, politique, statistique et minéralogique : sur léchelle de 1/1641836 ou d'une ligne par 1900 toises
|x|pudl0028|attn|Attention and effort
|x|pudl0063|2274590|La Boîte à joujoux : ballet pour enfants
|x|pudl0063|morrison|La Boîte à joujoux : ballet pour enfants
|x|pudl0065|1425104|The cause of the riots in the Yangtse Valley : A "complete picture gallery"
|x|pudl0115|6100740|Cedid atlas tercümesi
|x|pudl0130|8555444|[Engelmann Archive of Proofs and Samples]
|x|pudl0008|568784|Gender in the academy : women and learning from Plato to Princeton : an exhibition celebrating the 20th anniversary of undergraduate coeducation at Princeton University
|x|pudl0089|2011|Going to a fight.[Illustra]ting the sporting world in all its variety of style and costume along the road from Hyde Park Corner to Moulsey Hurst
|x|pudl0027|5235027|Histoire naturelle de Mre. Francois Bacon ...
||pudl0018|t12a|**Ivan Susanin** -this seems to be part of UPenn's Collection.  Making separate ticket for this one and contacting SC folks. 
|x|pudl0069|3777106|Manuel de l'outillage des arts et métiers : à l'usage des écoles techniques, compagnies de chemins de fer et de navigation : traitant de l'outillage du menuisier, tourneur, tonnelier, charron, charpentier, modeleur et du mécanicien
|x|pudl0059|2087793|Manuscript on the Veronese School of Painting
|x|pudl0084|2005|Mister O’Squat: A Panorama
|x|pudl0105|440627|Philip the Fair and the empire : a research report
|x|pudl0060|5954033|[Photography album documenting the Morant Bay Rebellion in Jamaica (1865), the Indian Northwest Frontier Hazara Campaign (1867-1870), views of Malta, Ireland, Guernsey, Spain, and elsewhere]
|x|pudl0085|616847|Pianta delle fabriche esistenti nella Villa Adriana
|x|pudl0022|4623565|Prospetto d[ell']alma città di Roma visto dal Monte Gianicolo : f. sotto gli avspicj della Sac. Maestà Cattol. di Carlo III re delle Spagne pio givsto magnifico promotore eccelso delle scienze e delle arti
|x|pudl0013|4616930|Il regno tvtto di Candia : delineato a parte
|x|pudl0024|v1|Reports of the Princeton University expeditions to Patagonia, 1896-1899
|x|pudl0034|gc131|Richard Willats's album
|x|pudl0011|1745946|Six ethnographical maps : illustrative of "The natural history of man," and "Researches into the physical history of mankind."
|x|pudl0120|3421283|Specimens of paper with different water marks, 1377-1840
|x|pudl0067|5589790|Teutsche Academie der Bau-Bildhauer- und Maler-Kunst : worinn die Regeln und Lehrsätze dieser Künste gegeben, nicht weniger zu mehrerer Erläuterung die besten Exempel der alten und neuen Künstler in Kupfer beygefüget worden, wie solche in Rom auf das genaueste abgezeichnet sind : nebst den Lebensbeschreibungen der besten griechischen, römischen und neuen Künstler, ingleichen der Anzeige ihrer vornehmsten Werke
|x|pudl0130|gc060|The Princeton Print Club 1941-1945

**Comment by kelea99** [comment] 2021-04-29 14:02
The items not in figgy, @cwulfman . Im completing everything else:
1. pudl0130	8555444	[Engelmann Archive of Proofs and Samples]
2. pudl0018	t12a	Ivan Susanin 
3. Volume 2 for : Manuel de l'outillage des arts et métiers : à l'usage des écoles techniques, compagnies de chemins de fer et de navigation : traitant de l'outillage du menuisier, tourneur, tonnelier, charron, charpentier, modeleur et du mécanicien
4. pudl0120	3421283	Specimens of paper with different water marks, 1377-1840

**Comment by kelea99** [comment] 2021-08-10 17:32
- We do have engelman:https://catalog.princeton.edu/catalog/9985554443506421. But i still cannot find it in figgy (it has to be there, though).

- Ivan susanin seems to be a university of pennsylvania item? wrote to @cwulfman and @escowles about this one.

- Volume 2 ingested by KEL for Manuel de l'outillage des arts et metiers. https://figgy.princeton.edu/catalog/77362f63-2fe4-4527-b1c3-eae5e60618d8

- speciments of paper with different water marks is there. https://figgy.princeton.edu/catalog/bb133ab0-bd26-41a4-87df-970e3e5260a6

**Comment by escowles** [comment] 2021-08-10 17:38
@kelea99 

Here is the Engelman object in figgy: https://figgy.princeton.edu/catalog/49add4a8-e4fc-4ddf-a533-b335f9b21b18

Agree about the Ivan Susanin item (it has Penn bookplates, etc.) so it's weird that we would digitize it

**Comment by kelea99** [comment] 2021-08-10 17:41
Thank you!! @escowles Is there a reason why Engelmann does not come up in any searches I try? How did you find it? I tried the bib id, the title, and the author.

**Comment by escowles** [comment] 2021-08-10 17:52
I tried searching for the Bib and got a weird error (maybe related to the Voyager/Alma difference?). So then I went to the viewer, got the IIIF manifest URL, and got the figgy ID from there.

**Comment by kelea99** [comment] 2021-08-10 17:57
Ok. Good to know. I think I'll make a ticket for Engelmann, just in case it is a bug that has his more than one item in figgy. at least we have something to go off of.  Thank you @escowles 

@cwulfman. I am going to close this ticket and make a ticket specifically for Ivan Susanin. We need curator weigh in on that one, imo. We do have the images for T.12a, 12b and 12 supplement on the Isilon, under its pudl number (PUDL0018). we would lose its structure that is in PUDL.

**Closed as completed** 2021-08-10 18:07 UTC
Labels: migrate
